glyphs = (
    ('ambulance', 'Ambulance'),
    ('anchor', 'Anchor'),
    ('android', 'Android'),
    ('angle-down', 'Angle: Down'),
    ('angle-double-down', 'Angle: Down (Double)'),
    ('angle-left', 'Angle: Left'),
    ('angle-double-left', 'Angle: Left (Double)'),
    ('angle-right', 'Angle: Right'),
    ('angle-double-right', 'Angle: Right (Double)'),
    ('angle-up', 'Angle: Up'),
    ('angle-double-up', 'Angle: Up (Double)'),
    ('apple', 'Apple'),
    ('archive', 'Archive'),
    ('arrow-down', 'Arrow: Down'),
    ('arrow-circle-down', 'Arrow: Down (Circle)'),
    ('arrow-circle-o-down', 'Arrow: Down (Circle-O)'),
    ('arrow-left', 'Arrow (Left)'),
    ('arrow-circle-left', 'Arrow: Left (Circle)'),
    ('arrow-circle-o-left', 'Arrow: Left (Circle-O)'),
    ('arrow-right', 'Arrow: Right'),
    ('arrow-circle-right', 'Arrow: Right (Circle)'),
    ('arrow-circle-o-right', 'Arrow: Right (Circle-O)'),
    ('arrow-up', 'Arrow: Up'),
    ('arrow-circle-up', 'Arrow: Up (Circle)'),
    ('arrow-circle-o-up', 'Arrow: Up (Circle-O)'),
    ('arrows', 'Arrows'),
    ('arrows-alt', 'Arrows (Alt)'),
    ('arrows-h', 'Arrows: Horizontal'),
    ('arrows-v', 'Arrows: Vertical'),
    ('asterisk', 'Asterisk'),
    ('automobile', 'Automobile'),
    ('backward', 'Backward'),
    ('ban', 'Ban'),
    ('bank', 'Bank'),
    ('bar-chart-o', 'Bar Chart (O)'),
    ('barcode', 'Barcode'),
    ('bars', 'Bars'),
    ('beer', 'Beer'),
    ('behance', 'Behance'),
    ('behance-square', 'Behance (Square)'),
    ('bell', 'Bell'),
    ('bell-o', 'Bell (O)'),
    ('bitbucket', 'BitBucket'),
    ('bitbucket-square', 'BitBucket (Square)'),
    ('bitcoin', 'Bitcoin'),
    ('bold', 'Bold'),
    ('bolt', 'Bolt'),
    ('bomb', 'Bomb'),
    ('book', 'Book'),
    ('bookmark', 'Bookmark'),
    ('bookmark-o', 'Bookmark (O)'),
    ('briefcase', 'Briefcase'),
    ('btc', 'BTC'),
    ('bug', 'Bug'),
    ('building', 'Building'),
    ('building-o', 'Building (O)'),
    ('bullhorn', 'Bullhorn'),
    ('bullseye', 'Bullseye'),
    ('cab', 'Cab'),
    ('calendar', 'Calendar'),
    ('calendar-o', 'Calendar (O)'),
    ('camera', 'Camera'),
    ('camera-retro', 'Camera (Retro)'),
    ('car', 'Car'),
    ('caret-down', 'Caret: Down'),
    ('caret-square-o-down', 'Caret: Down (Square-O)'),
    ('caret-left', 'Caret: Left'),
    ('caret-square-o-left', 'Caret: Left (Square-O)'),
    ('caret-right', 'Caret: Right'),
    ('caret-square-o-right', 'Caret: Right (Square-O)'),
    ('caret-up', 'Caret: Up'),
    ('caret-square-o-up', 'Caret: Up (Square-O)'),
    ('certificate', 'Certificate'),
    ('chain', 'Chain'),
    ('chain-broken', 'Chain (Broken)'),
    ('check', 'Check'),
    ('check-circle', 'Check (Circle)'),
    ('check-circle-o', 'Check (Circle-O)'),
    ('check-square', 'Check (Square)'),
    ('check-square-o', 'Check (Square-O)'),
    ('chevron-down', 'Chevron: Down'),
    ('chevron-circle-down', 'Chevron: Down (Circle)'),
    ('chevron-left', 'Chevron: Left'),
    ('chevron-circle-left', 'Chevron: Left (Circle)'),
    ('chevron-right', 'Chevron: Right'),
    ('chevron-circle-right', 'Chevron: Right (Circle)'),
    ('chevron-up', 'Chevron: Up'),
    ('chevron-circle-up', 'Chevron: Up (Circle)'),
    ('child', 'Child'),
    ('circle', 'Circle'),
    ('circle-o', 'Circle (O)'),
    ('circle-o-notch', 'Circle (O Notch)'),
    ('circle-thin', 'Circle (Thin)'),
    ('clipboard', 'Clipboard'),
    ('clock-o', 'Clock (O)'),
    ('cloud', 'Cloud'),
    ('cloud-download', 'Cloud: Download'),
    ('cloud-upload', 'Cloud: Upload'),
    ('cny', 'CNY'),
    ('code', 'Code'),
    ('code-fork', 'Code (Fork)'),
    ('codepen', 'Codepen'),
    ('coffee', 'Coffee'),
    ('cog', 'Cog'),
    ('cogs', 'Cogs'),
    ('columns', 'Columns'),
    ('comment', 'Comment'),
    ('comment-o', 'Comment (O)'),
    ('comments', 'Comments'),
    ('comments-o', 'Comments (O)'),
    ('compass', 'Compass'),
    ('compress', 'Compress'),
    ('copy', 'Copy'),
    ('credit-card', 'Credit (Card)'),
    ('crop', 'Crop'),
    ('crosshairs', 'Crosshairs'),
    ('css3', 'CSS3'),
    ('cube', 'Cube'),
    ('cubes', 'Cubes'),
    ('cut', 'Cut'),
    ('cutlery', 'Cutlery'),
    ('dashboard', 'Dashboard'),
    ('database', 'Database'),
    ('dedent', 'Dedent'),
    ('delicious', 'Delicious'),
    ('desktop', 'Desktop'),
    ('deviantart', 'Deviantart'),
    ('digg', 'Digg'),
    ('dollar', 'Dollar'),
    ('dot-circle-o', 'Dot (Circle-O)'),
    ('download', 'Download'),
    ('dribbble', 'Dribbble'),
    ('dropbox', 'Dropbox'),
    ('drupal', 'Drupal'),
    ('edit', 'Edit'),
    ('eject', 'Eject'),
    ('ellipsis-h', 'Ellipsis (Horizontal)'),
    ('ellipsis-v', 'Ellipsis (Vertical)'),
    ('empire', 'Empire'),
    ('envelope', 'Envelope'),
    ('envelope-o', 'Envelope (O)'),
    ('envelope-square', 'Envelope (Square)'),
    ('eraser', 'Eraser'),
    ('eur', 'EUR'),
    ('euro', 'Euro'),
    ('exchange', 'Exchange'),
    ('exclamation', 'Exclamation'),
    ('exclamation-circle', 'Exclamation (Circle)'),
    ('exclamation-triangle', 'Exclamation (Triangle)'),
    ('expand', 'Expand'),
    ('external-link', 'External Link'),
    ('external-link-square', 'External Link (Square)'),
    ('eye', 'Eye'),
    ('eye-slash', 'Eye (Slash)'),
    ('facebook', 'Facebook'),
    ('facebook-square', 'Facebook (Square)'),
    ('fast-backward', 'Fast Rewind'),
    ('fast-forward', 'Fast Forward'),
    ('fax', 'Fax'),
    ('female', 'Female'),
    ('fighter-jet', 'Fighter Jet'),
    ('file', 'File'),
    ('file-o', 'File (O)'),
    ('files-o', 'Files (O)'),
    ('file-archive-o', 'File: Archive (O)'),
    ('file-audio-o', 'File: Audio (O)'),
    ('file-code-o', 'File: Code (O)'),
    ('file-excel-o', 'File: Excel (O)'),
    ('file-image-o', 'File: Image (O)'),
    ('file-movie-o', 'File: Movie (O)'),
    ('file-pdf-o', 'File: PDF (O)'),
    ('file-photo-o', 'File: Photo (O)'),
    ('file-picture-o', 'File: Picture (O)'),
    ('file-powerpoint-o', 'File: Powerpoint (O)'),
    ('file-sound-o', 'File: Sound (O)'),
    ('file-text', 'File: Text'),
    ('file-text-o', 'File: Text (O)'),
    ('file-video-o', 'File: Video (O)'),
    ('file-word-o', 'File: Word (O)'),
    ('file-zip-o', 'File: Zip (O)'),
    ('film', 'Film'),
    ('filter', 'Filter'),
    ('fire', 'Fire'),
    ('fire-extinguisher', 'Fire Extinguisher'),
    ('flag', 'Flag'),
    ('flag-o', 'Flag (O)'),
    ('flag-checkered', 'Flag: Checkered'),
    ('flash', 'Flash'),
    ('flask', 'Flask'),
    ('flickr', 'Flickr'),
    ('floppy-o', 'Floppy (O)'),
    ('folder', 'Folder'),
    ('folder-o', 'Folder (O)'),
    ('folder-open', 'Folder: Open'),
    ('folder-open-o', 'Folder: Open (O)'),
    ('font', 'Font'),
    ('forward', 'Forward'),
    ('foursquare', 'Foursquare'),
    ('frown-o', 'Frown (O)'),
    ('gamepad', 'Gamepad'),
    ('gavel', 'Gavel'),
    ('gbp', 'GBP'),
    ('ge', 'Ge'),
    ('gear', 'Gear'),
    ('gears', 'Gears'),
    ('gift', 'Gift'),
    ('git', 'Git'),
    ('git-square', 'Git (Square)'),
    ('github', 'GitHub'),
    ('github-alt', 'GitHub (Alt)'),
    ('github-square', 'GitHub (Square)'),
    ('gittip', 'GitTip'),
    ('glass', 'Glass'),
    ('globe', 'Globe'),
    ('google', 'Google'),
    ('google-plus', 'Google Plus'),
    ('google-plus-square', 'Google Plus (Square)'),
    ('graduation-cap', 'Graduation (Cap)'),
    ('group', 'Group'),
    ('h-square', 'H (Square)'),
    ('hacker-news', 'Hacker News'),
    ('hand-o-down', 'Hand: Down (O)'),
    ('hand-o-left', 'Hand: Left (O)'),
    ('hand-o-right', 'Hand: Right (O)'),
    ('hand-o-up', 'Hand: Up (O)'),
    ('hdd-o', 'HDD (O)'),
    ('header', 'Header'),
    ('headphones', 'Headphones'),
    ('heart', 'Heart'),
    ('heart-o', 'Heart (O)'),
    ('history', 'History'),
    ('home', 'Home'),
    ('hospital-o', 'Hospital (O)'),
    ('html5', 'HTML5'),
    ('image', 'Image'),
    ('inbox', 'Inbox'),
    ('indent', 'Indent'),
    ('info', 'Info'),
    ('info-circle', 'Info (Circle)'),
    ('inr', 'Inr'),
    ('instagram', 'Instagram'),
    ('institution', 'Institution'),
    ('italic', 'Italic'),
    ('joomla', 'Joomla'),
    ('jpy', 'JPY'),
    ('jsfiddle', 'JSFiddle'),
    ('key', 'Key'),
    ('keyboard-o', 'Keyboard (O)'),
    ('krw', 'KRW'),
    ('language', 'Language'),
    ('laptop', 'Laptop'),
    ('leaf', 'Leaf'),
    ('legal', 'Legal'),
    ('lemon-o', 'Lemon (O)'),
    ('level-down', 'Level Down'),
    ('level-up', 'Level Up'),
    ('life-bouy', 'Life Bouy'),
    ('life-ring', 'Life Ring'),
    ('life-saver', 'Life Saver'),
    ('lightbulb-o', 'Lightbulb (O)'),
    ('link', 'Link'),
    ('linkedin', 'LinkedIn'),
    ('linkedin-square', 'LinkedIn (Square)'),
    ('linux', 'Linux'),
    ('list', 'List'),
    ('list-alt', 'List (Alt)'),
    ('list-ol', 'List (Ol)'),
    ('list-ul', 'List (Ul)'),
    ('location-arrow', 'Location (Arrow)'),
    ('lock', 'Lock'),
    ('long-arrow-down', 'Long Arrow Down'),
    ('long-arrow-left', 'Long Arrow Left'),
    ('long-arrow-right', 'Long Arrow Right'),
    ('long-arrow-up', 'Long Arrow Up'),
    ('magic', 'Magic'),
    ('magnet', 'Magnet'),
    ('mail-forward', 'Mail: Forward'),
    ('mail-reply', 'Mail: Reply'),
    ('mail-reply-all', 'Mail: Reply All'),
    ('male', 'Male'),
    ('map-marker', 'Map Marker'),
    ('maxcdn', 'MaxCDN'),
    ('medkit', 'Medkit'),
    ('meh-o', 'Meh (O)'),
    ('microphone', 'Microphone'),
    ('microphone-slash', 'Microphone (Slash)'),
    ('minus', 'Minus'),
    ('minus-circle', 'Minus (Circle)'),
    ('minus-square', 'Minus (Square)'),
    ('minus-square-o', 'Minus (Square O)'),
    ('mobile', 'Mobile'),
    ('mobile-phone', 'Mobile Phone'),
    ('money', 'Money'),
    ('moon-o', 'Moon (O)'),
    ('mortar-board', 'Mortar Board'),
    ('music', 'Music'),
    ('navicon', 'Navicon'),
    ('openid', 'Openid'),
    ('outdent', 'Outdent'),
    ('pagelines', 'Pagelines'),
    ('paper-plane', 'Paper Plane'),
    ('paper-plane-o', 'Paper Plane (O)'),
    ('paperclip', 'Paper Clip'),
    ('paragraph', 'Paragraph'),
    ('paste', 'Paste'),
    ('pause', 'Pause'),
    ('paw', 'Paw'),
    ('pencil', 'Pencil'),
    ('pencil-square', 'Pencil (Square)'),
    ('pencil-square-o', 'Pencil (Square-O)'),
    ('phone', 'Phone'),
    ('phone-square', 'Phone (Square)'),
    ('photo', 'Photo'),
    ('picture-o', 'Picture (O)'),
    ('pied-piper', 'Pied Piper'),
    ('pied-piper-alt', 'Pied Piper (Alt)'),
    ('pied-piper-square', 'Pied Piper (Square)'),
    ('pinterest', 'Pinterest'),
    ('pinterest-square', 'Pinterest (Square)'),
    ('plane', 'Plane'),
    ('play', 'Play'),
    ('play-circle', 'Play (Circle)'),
    ('play-circle-o', 'Play (Circle-O)'),
    ('plus', 'Plus'),
    ('plus-circle', 'Plus (Circle)'),
    ('plus-square', 'Plus (Square)'),
    ('plus-square-o', 'Plus (Square-O)'),
    ('power-off', 'Power Off'),
    ('print', 'Print'),
    ('puzzle-piece', 'Puzzle Piece'),
    ('qq', 'Qq'),
    ('qrcode', 'QR Code'),
    ('question', 'Question'),
    ('question-circle', 'Question (Circle)'),
    ('quote-left', 'Quote: Left'),
    ('quote-right', 'Quote: Right'),
    ('ra', 'Ra'),
    ('random', 'Random'),
    ('rebel', 'Rebel'),
    ('recycle', 'Recycle'),
    ('reddit', 'Reddit'),
    ('reddit-square', 'Reddit (Square)'),
    ('refresh', 'Refresh'),
    ('renren', 'Renren'),
    ('reorder', 'Reorder'),
    ('repeat', 'Repeat'),
    ('reply', 'Reply'),
    ('reply-all', 'Reply All'),
    ('retweet', 'Retweet'),
    ('rmb', 'Rmb'),
    ('road', 'Road'),
    ('rocket', 'Rocket'),
    ('rotate-left', 'Rotate Left'),
    ('rotate-right', 'Rotate Right'),
    ('rouble', 'Rouble'),
    ('rss', 'RSS'),
    ('rss-square', 'RSS (Square)'),
    ('rub', 'Rub'),
    ('ruble', 'Ruble'),
    ('rupee', 'Rupee'),
    ('save', 'Save'),
    ('scissors', 'Scissors'),
    ('search', 'Search'),
    ('search-minus', 'Search: Minus'),
    ('search-plus', 'Search: Plus'),
    ('send', 'Send'),
    ('send-o', 'Send (O)'),
    ('share', 'Share'),
    ('share-alt', 'Share (Alt)'),
    ('share-alt-square', 'Share (Alt Square)'),
    ('share-square', 'Share (Square)'),
    ('share-square-o', 'Share (Square-O)'),
    ('shield', 'Shield'),
    ('shopping-cart', 'Shopping Cart'),
    ('sign-in', 'Sign In'),
    ('sign-out', 'Sign Out'),
    ('signal', 'Signal'),
    ('sitemap', 'Sitemap'),
    ('skype', 'Skype'),
    ('slack', 'Slack'),
    ('sliders', 'Sliders'),
    ('smile-o', 'Smile (O)'),
    ('sort', 'Sort'),
    ('sort-asc', 'Sort: Asc'),
    ('sort-desc', 'Sort: Desc'),
    ('sort-down', 'Sort: Down'),
    ('sort-up', 'Sort: Up'),
    ('sort-alpha-asc', 'Sort: Alpha Asc'),
    ('sort-alpha-desc', 'Sort: Alpha Desc'),
    ('sort-amount-asc', 'Sort: Amount Asc'),
    ('sort-amount-desc', 'Sort: Amount Desc'),
    ('sort-numeric-asc', 'Sort: Numeric Asc'),
    ('sort-numeric-desc', 'Sort: Numeric Desc'),
    ('soundcloud', 'Soundcloud'),
    ('space-shuttle', 'Space Shuttle'),
    ('spinner', 'Spinner'),
    ('spoon', 'Spoon'),
    ('spotify', 'Spotify'),
    ('square', 'Square'),
    ('square-o', 'Square (O)'),
    ('stack-exchange', 'Stack Exchange'),
    ('stack-overflow', 'Stack Overflow'),
    ('star', 'Star'),
    ('star-half', 'Star (Half)'),
    ('star-half-empty', 'Star (Half Empty)'),
    ('star-half-full', 'Star (Half Full)'),
    ('star-half-o', 'Star (Half O)'),
    ('star-o', 'Star (O)'),
    ('steam', 'Steam'),
    ('steam-square', 'Steam (Square)'),
    ('step-backward', 'Step Backward'),
    ('step-forward', 'Step Forward'),
    ('stethoscope', 'Stethoscope'),
    ('stop', 'Stop'),
    ('strikethrough', 'Strikethrough'),
    ('stumbleupon', 'Stumbleupon'),
    ('stumbleupon-circle', 'Stumbleupon (Circle)'),
    ('subscript', 'Subscript'),
    ('suitcase', 'Suitcase'),
    ('sun-o', 'Sun (O)'),
    ('superscript', 'Superscript'),
    ('support', 'Support'),
    ('table', 'Table'),
    ('tablet', 'Tablet'),
    ('tachometer', 'Tachometer'),
    ('tag', 'Tag'),
    ('tags', 'Tags'),
    ('tasks', 'Tasks'),
    ('taxi', 'Taxi'),
    ('tencent-weibo', 'Tencent Weibo'),
    ('terminal', 'Terminal'),
    ('text-height', 'Text Height'),
    ('text-width', 'Text Width'),
    ('th', 'Th'),
    ('th-large', 'Th (Large)'),
    ('th-list', 'Th (List)'),
    ('thumb-tack', 'Thumb Tack'),
    ('thumbs-down', 'Thumbs Down'),
    ('thumbs-o-down', 'Thumbs Down (O)'),
    ('thumbs-up', 'Thumbs Up'),
    ('thumbs-o-up', 'Thumbs Up (O)'),
    ('ticket', 'Ticket'),
    ('times', 'Times'),
    ('times-circle', 'Times (Circle)'),
    ('times-circle-o', 'Times (Circle O)'),
    ('tint', 'Tint'),
    ('toggle-down', 'Toggle Down'),
    ('toggle-left', 'Toggle Left'),
    ('toggle-right', 'Toggle Right'),
    ('toggle-up', 'Toggle Up'),
    ('trash-o', 'Trash (O)'),
    ('tree', 'Tree'),
    ('trello', 'Trello'),
    ('trophy', 'Trophy'),
    ('truck', 'Truck'),
    ('try', 'Try'),
    ('tumblr', 'Tumblr'),
    ('tumblr-square', 'Tumblr (Square)'),
    ('turkish-lira', 'Turkish Lira'),
    ('twitter', 'Twitter'),
    ('twitter-square', 'Twitter (Square)'),
    ('umbrella', 'Umbrella'),
    ('underline', 'Underline'),
    ('undo', 'Undo'),
    ('university', 'University'),
    ('unlink', 'Unlink'),
    ('unlock', 'Unlock'),
    ('unlock-alt', 'Unlock (Alt)'),
    ('unsorted', 'Unsorted'),
    ('upload', 'Upload'),
    ('usd', 'USD'),
    ('user', 'User'),
    ('user-md', 'User (MD)'),
    ('users', 'Users'),
    ('video-camera', 'Video (Camera)'),
    ('vimeo-square', 'Vimeo (Square)'),
    ('vine', 'Vine'),
    ('vk', 'Vk'),
    ('volume-up', 'Volume Up'),
    ('volume-down', 'Volume Down'),
    ('volume-off', 'Volume Off'),
    ('warning', 'Warning'),
    ('wechat', 'Wechat'),
    ('weibo', 'Weibo'),
    ('weixin', 'Weixin'),
    ('wheelchair', 'Wheelchair'),
    ('windows', 'Windows'),
    ('won', 'Won'),
    ('wordpress', 'Wordpress'),
    ('wrench', 'Wrench'),
    ('xing', 'Xing'),
    ('xing-square', 'Xing (Square)'),
    ('yahoo', 'Yahoo'),
    ('yen', 'Yen'),
    ('youtube', 'Youtube'),
    ('youtube-play', 'Youtube (Play)'),
    ('youtube-square', 'Youtube (Square)'),
)